version: '3'
services:
  certbot:
    build:
      context: .
      dockerfile: certbot.Dockerfile
    container_name: certbot
    volumes:
      - certs:/etc/letsencrypt:rw
      - certs:/var/lib/letsencrypt:rw
      - certs:/var/cloudflare.ini
    restart: unless-stopped
    env_file:
      - .env
    environment:
      APP_DOMAIN: $APP_DOMAIN
      DOMAIN: $DOMAIN
      OTHER_LEVEL_DOMAINS: $OTHER_LEVEL_DOMAINS
      EMAIL: $EMAIL
    healthcheck:
      test: [ "CMD-SHELL", "[ -f /etc/letsencrypt/live/umaiden.ru/fullchain.pem ]" ]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - $CERTBOT_PORT:$CERTBOT_PORT

  envoy:
    build:
      context: .
      dockerfile: envoy.Dockerfile
    environment:
      GRPC_SERVER_HOST: $GRPC_SERVER_HOST
      GRPC_SERVER_PORT: $GRPC_SERVER_PORT
      ENVOY_PORT: $ENVOY_PORT
      CERTIFICATE_CHAIN_FILENAME_PATH: $CERTIFICATE_CHAIN_FILENAME_PATH
      PRIVATE_KEY_FILENAME_PATH: $PRIVATE_KEY_FILENAME_PATH
      BACKEND_DOMAIN: $BACKEND_DOMAIN
      DOMAIN: $DOMAIN
      APP_DOMAIN: $APP_DOMAIN
      APP_HOST: $APP_HOST
      APP_PORT: $APP_PORT
      CERTBOT_PORT: $CERTBOT_PORT
    env_file:
      - .env
    networks:
      - web-game-deck
    ports:
      - $ENVOY_PORT:$ENVOY_PORT
    volumes:
      - ./envoy.template.yaml:/etc/envoy/envoy.template.yaml
      - certs:/var/lib/letsencrypt:ro
      - ./src/proto/generated/gateway.pb:/etc/envoy/gateway.pb
    depends_on:
      certbot:
        condition: service_healthy
  web:
    build:
      context: .
    environment:
      GMAIL_EXTERNAL_PASSWORD: $GMAIL_EXTERNAL_PASSWORD
      REACT_PORT: $REACT_PORT
      ENVOY_PORT: $ENVOY_PORT
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - envoy
    networks:
      - web-game-deck

volumes:
  certs:
    external: true

networks:
  web-game-deck:
    driver: bridge
