version: '3'
services:
  envoy:
    build:
      context: .
      dockerfile: envoy.Dockerfile
    environment:
      GRPC_SERVER_HOST: ${GRPC_SERVER_HOST}
      GRPC_SERVER_PORT: ${GRPC_SERVER_PORT}
      ENVOY_PORT: ${ENVOY_PORT}
    networks:
      - web-game-deck
    ports:
      - ${ENVOY_PORT}:${ENVOY_PORT}
    extra_hosts:
      - "remote-server:185.236.23.87"
    volumes:
      - ./envoy.template.yaml:/etc/envoy/envoy.template.yaml
  web:
    build:
      context: .
    environment:
      REACT_PORT: ${REACT_PORT}
      ENVOY_PORT: ${ENVOY_PORT}
    ports:
      - ${REACT_PORT}:3000
    networks:
      - web-game-deck

networks:
  web-game-deck:
    driver: bridge
