version: '3'
services:
  envoy:
    build:
      context: .
      dockerfile: envoy.Dockerfile
    environment:
      GRPC_SERVER_HOST: $GRPC_SERVER_HOST
      GRPC_SERVER_PORT: $GRPC_SERVER_PORT
      ENVOY_PORT: $ENVOY_PORT
      CERTIFICATE_CHAIN_FILENAME_PATH: $CERTIFICATE_CHAIN_FILENAME_PATH
      PRIVATE_KEY_FILENAME_PATH: $PRIVATE_KEY_FILENAME_PATH
      BACKEND_DOMAIN: $BACKEND_DOMAIN
      DOMAIN: $DOMAIN
    env_file:
      - .env
    networks:
      - web-game-deck
    ports:
      - $ENVOY_PORT:$ENVOY_PORT
    volumes:
      - ./envoy.template.yaml:/etc/envoy/envoy.template.yaml
      - certs:/var/www/certbot/:ro
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - certs:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    command: certonly --standalone --agree-tos --non-interactive --email www.www-we2016@mail.ru -d teamspot.online
    ports:
      - $CERTBOT_PORT:$CERTBOT_PORT
  web:
    build:
      context: .
    environment:
      REACT_PORT: $REACT_PORT
      ENVOY_PORT: $ENVOY_PORT
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - web-game-deck

volumes:
  certs:
    external: true

networks:
  web-game-deck:
    driver: bridge
