version: '3'
services:
  envoy:
    build:
      context: .
      dockerfile: envoy.Dockerfile
    environment:
      GRPC_SERVER_HOST: $GRPC_SERVER_HOST
      GRPC_SERVER_PORT: $GRPC_SERVER_PORT
      ENVOY_PORT: $ENVOY_PORT
    env_file:
      - .env
    networks:
      - web-game-deck
    ports:
      - $ENVOY_PORT:$ENVOY_PORT
    volumes:
      - ./envoy.template.yaml:/etc/envoy/envoy.template.yaml
  web:
    build:
      context: .
    environment:
      REACT_PORT: $REACT_PORT
      ENVOY_PORT: $ENVOY_PORT
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - web-game-deck

networks:
  web-game-deck:
    driver: bridge
