version: '3'
services:
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - certs:/etc/letsencrypt:rw
      - certs:/var/lib/letsencrypt:rw
    command: certonly --standalone --agree-tos --non-interactive --email www.www-we2016@mail.ru -d teamspot.online
    ports:
      - $CERTBOT_PORT:$CERTBOT_PORT
  renew:
    image: certbot/dns-cloudflare
    container_name: certbot-renew
    volumes:
      - certs:/etc/letsencrypt:rw
      - certs:/var/lib/letsencrypt:rw
    entrypoint: "/bin/sh -c 'while :; do certbot renew --dns-cloudflare --dns-cloudflare-credentials /cfg/cloudflare.ini; sleep 12h; done'"

  envoy:
    build:
      context: .
      dockerfile: envoy.Dockerfile
    environment:
      GRPC_SERVER_HOST: $GRPC_SERVER_HOST
      GRPC_SERVER_PORT: $GRPC_SERVER_PORT
      ENVOY_PORT: $ENVOY_PORT
      CERTIFICATE_CHAIN_FILENAME_PATH: $CERTIFICATE_CHAIN_FILENAME_PATH
      PRIVATE_KEY_FILENAME_PATH: $PRIVATE_KEY_FILENAME_PATH
      BACKEND_DOMAIN: $BACKEND_DOMAIN
      DOMAIN: $DOMAIN
      CERTBOT_PORT: $CERTBOT_PORT
    env_file:
      - .env
    networks:
      - web-game-deck
    ports:
      - $ENVOY_PORT:$ENVOY_PORT
    volumes:
      - ./envoy.template.yaml:/etc/envoy/envoy.template.yaml
      - certs:/var/lib/letsencrypt:ro
    depends_on:
      - certbot
  web:
    build:
      context: .
    environment:
      GMAIL_EXTERNAL_PASSWORD: $GMAIL_EXTERNAL_PASSWORD
      REACT_PORT: $REACT_PORT
      ENVOY_PORT: $ENVOY_PORT
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - envoy
    networks:
      - web-game-deck

volumes:
  certs:
    external: true

networks:
  web-game-deck:
    driver: bridge
