# See : https://taskfile.dev/api/

version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - protoc -I=src/proto src/proto/*.proto --js_out=import_style=commonjs,binary:src/proto --grpc-web_out=import_style=commonjs,mode=grpcwebtext:src/proto